### PR TITLE
Options

### LINKED ISSUE #2: Move entry points to `src`
If everything is moved to a `src` directory and then bundled into the root, you won't need to name things like `bundledBackground.js` and it can just be `background.js`

### PR DESCRIPTION
**Pull request by alysonz**
#### What's this PR do?

Adds a popup menu to the plugin that allows for enabling and disabling the plugin. Adds an options page that allows for editing the url at which the template resides. It also organizes types of files into folders.
#### Where should the reviewer start?

Popup.js is where all the new events are triggered. When the Disable/Enable option is selected it sends a message to fillPullBody.js. It also sets an event listener for the options page.
#### How should this be manually tested?

Pull down and install the plugin, toggle the Enable/Disable options, open the option page, try to set a new url.
#### What are the relevant tickets?

closes iceddev/git-splainin#2
#### Any background context you want to provide?

The popup and the options pages will eventually/soon be using react instead. Also, we haven't started doing any es6 yet, but that's next.

### CODE REVIEW

**Comment by phated** [comment]
I tried setting the URL to pull the template from but it doesn't seem to update.  Thoughts?

**Comment by alysonz** [comment]
Fixed.

**Comment by phated** [comment]
@alysonz you missed adding `babel-loader` as a devDependency so my build didn't actually happen

**Comment by warbrett** [comment]
This has been updated.

**Pull request merged**
